name: final_project_iti
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  cloud_firestore: ^6.0.0
  cupertino_icons: ^1.0.8
  device_preview: ^1.3.1
  dio: ^5.9.0
  dotted_border: ^3.1.0
  equatable: ^2.0.5
  file_picker: ^10.3.1
  firebase_core: ^4.0.0
  floating_draggable_widget: ^2.3.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_chat_core: ^2.8.0
  flutter_chat_ui: ^2.9.0
  flutter_dotenv: ^5.2.1
  flutter_gemini: ^3.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.6
  flutter_screenutil: ^5.9.3
  flutter_slider_drawer: ^3.0.2
  flutter_svg: ^2.2.0
  gap: ^3.0.1
  image_picker: ^1.1.2
  intl: ^0.20.2
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  persistent_bottom_nav_bar: ^6.2.1
  shared_preferences: ^2.5.3
  smooth_page_indicator: ^1.2.1
  timeline_tile: ^2.0.0
  url_launcher: ^6.3.2
  uuid: ^4.5.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - .env

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter_28pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter/Inter_28pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter/Inter_28pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter/Inter_28pt-Bold.ttf
          weight: 700
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/fonts/Tajawal/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/Tajawal/Tajawal-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto/Roboto-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Roboto/Roboto-SemiBold.ttf
          weight: 600

flutter_assets:
  assets_path: assets/images
  output_path: lib/core/utilities
  filename: assets_manager.dart
  field_prefix: null

flutter_intl:
  enabled: true

flutter_native_splash:
  android: true
  ios: true
  web: false

  # خلفية السبلش
  color: "#FFFFFF"
  color_dark: "#000000"

  # Android 12+ support
  android_12:
    color: "#FFFFFF"
    color_dark: "#000000"
    image: assets/images/backcolor_splash.jpg
    image_dark: assets/images/backcolor_splash2.jpg
    icon_background_color: "#FFFFFF"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.jpg"
