// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmDEYN8-6-dhHedoLjqq85ku0RR9aLDnA',
    appId: '1:367325102619:web:de37609bee883e7915eebe',
    messagingSenderId: '367325102619',
    projectId: 'iti-graduation-project-3f641',
    authDomain: 'iti-graduation-project-3f641.firebaseapp.com',
    storageBucket: 'iti-graduation-project-3f641.firebasestorage.app',
    measurementId: 'G-NXGDMFYPSX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxeIQqggp4LgzYEaVKMIaM380bRPY0Nxo',
    appId: '1:367325102619:android:e92023c3b96d484b15eebe',
    messagingSenderId: '367325102619',
    projectId: 'iti-graduation-project-3f641',
    storageBucket: 'iti-graduation-project-3f641.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEa8GTpYfowKf4CpBsGSHhYEXA1wTF4rY',
    appId: '1:367325102619:ios:a0ee80b2a15cb3d015eebe',
    messagingSenderId: '367325102619',
    projectId: 'iti-graduation-project-3f641',
    storageBucket: 'iti-graduation-project-3f641.firebasestorage.app',
    iosBundleId: 'com.example.finalProjectIti',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmDEYN8-6-dhHedoLjqq85ku0RR9aLDnA',
    appId: '1:367325102619:web:24e612aeec1fabdc15eebe',
    messagingSenderId: '367325102619',
    projectId: 'iti-graduation-project-3f641',
    authDomain: 'iti-graduation-project-3f641.firebaseapp.com',
    storageBucket: 'iti-graduation-project-3f641.firebasestorage.app',
    measurementId: 'G-M4HWC20GH1',
  );
}
